"""add academy models

Revision ID: 1c624d17536e
Revises: eb88c4bced62
Create Date: 2026-03-01 22:43:11.386530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c624d17536e'
down_revision: Union[str, None] = 'eb88c4bced62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academy_lessons',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('lesson_type', sa.String(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.Column('goal', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order')
    )
    with op.batch_alter_table('academy_lessons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_academy_lessons_id'), ['id'], unique=False)

    op.create_table('user_academy_progress',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('lesson_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['academy_lessons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_academy_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_academy_progress_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_academy_progress_lesson_id'), ['lesson_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_academy_progress_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('choirs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_users', sa.Integer(), nullable=True))

    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.alter_column('voice_part',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('SOPRANO', 'ALTO', 'TENOR', 'BASS', 'DIRECTOR', 'SUBDIRECTOR', name='voicepart'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.alter_column('voice_part',
               existing_type=sa.Enum('SOPRANO', 'ALTO', 'TENOR', 'BASS', 'DIRECTOR', 'SUBDIRECTOR', name='voicepart'),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)

    with op.batch_alter_table('choirs', schema=None) as batch_op:
        batch_op.drop_column('max_users')

    with op.batch_alter_table('user_academy_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_academy_progress_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_academy_progress_lesson_id'))
        batch_op.drop_index(batch_op.f('ix_user_academy_progress_id'))

    op.drop_table('user_academy_progress')
    with op.batch_alter_table('academy_lessons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_academy_lessons_id'))

    op.drop_table('academy_lessons')
    # ### end Alembic commands ###
