"""add_pipeline_fields_and_audit_log

Revision ID: 39926feca242
Revises: 8fd87df5b406
Create Date: 2026-02-28 20:54:53.219646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39926feca242'
down_revision: Union[str, None] = '8fd87df5b406'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('details', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('processing_status', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('processing_error', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('metadata_json', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('checksum', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('storage_key', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('size_bytes', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_assets_checksum'), ['checksum'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_processing_status'), ['processing_status'], unique=False)
        batch_op.create_unique_constraint('uq_asset_idempotency', ['edition_id', 'asset_type', 'checksum'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_constraint('uq_asset_idempotency', type_='unique')
        batch_op.drop_index(batch_op.f('ix_assets_processing_status'))
        batch_op.drop_index(batch_op.f('ix_assets_checksum'))
        batch_op.drop_column('size_bytes')
        batch_op.drop_column('storage_key')
        batch_op.drop_column('checksum')
        batch_op.drop_column('metadata_json')
        batch_op.drop_column('processing_error')
        batch_op.drop_column('processing_status')

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_event_type'))
        batch_op.drop_index(batch_op.f('ix_audit_log_entity_id'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
