"""add_academy_exercises

Revision ID: 417f65a2c3b2
Revises: 1c624d17536e
Create Date: 2026-03-02 10:58:28.391156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '417f65a2c3b2'
down_revision: Union[str, None] = '1c624d17536e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academy_exercises',
    sa.Column('lesson_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.String(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('solution', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['academy_lessons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('academy_exercises', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_academy_exercises_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_academy_exercises_lesson_id'), ['lesson_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('academy_exercises', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_academy_exercises_lesson_id'))
        batch_op.drop_index(batch_op.f('ix_academy_exercises_id'))

    op.drop_table('academy_exercises')
    # ### end Alembic commands ###
