"""Add choir details and user personal info

Revision ID: 4678b9954049
Revises: c66f1c34d45b
Create Date: 2026-03-04 16:27:41.149681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4678b9954049'
down_revision: Union[str, None] = 'c66f1c34d45b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('choirs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('social_address', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('director_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('director_phone', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('subdirector_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('subdirector_phone', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('president_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('president_phone', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('president_has_whatsapp', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('president_email', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('secretary_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('secretary_phone', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('secretary_has_whatsapp', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('secretary_email', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('treasurer_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('treasurer_phone', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('treasurer_has_whatsapp', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('treasurer_email', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('other_info', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('logo_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('cover_photo_url', sa.String(), nullable=True))

    with op.batch_alter_table('project_repertoire', schema=None) as batch_op:
        batch_op.add_column(sa.Column('work_id', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_project_repertoire_work_id'), ['work_id'], unique=False)
        batch_op.create_foreign_key(None, 'works', ['work_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dni', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('has_whatsapp', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('address')
        batch_op.drop_column('has_whatsapp')
        batch_op.drop_column('phone')
        batch_op.drop_column('dni')

    with op.batch_alter_table('project_repertoire', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_project_repertoire_work_id'))
        batch_op.drop_column('work_id')

    with op.batch_alter_table('choirs', schema=None) as batch_op:
        batch_op.drop_column('cover_photo_url')
        batch_op.drop_column('logo_url')
        batch_op.drop_column('other_info')
        batch_op.drop_column('treasurer_email')
        batch_op.drop_column('treasurer_has_whatsapp')
        batch_op.drop_column('treasurer_phone')
        batch_op.drop_column('treasurer_name')
        batch_op.drop_column('secretary_email')
        batch_op.drop_column('secretary_has_whatsapp')
        batch_op.drop_column('secretary_phone')
        batch_op.drop_column('secretary_name')
        batch_op.drop_column('president_email')
        batch_op.drop_column('president_has_whatsapp')
        batch_op.drop_column('president_phone')
        batch_op.drop_column('president_name')
        batch_op.drop_column('subdirector_phone')
        batch_op.drop_column('subdirector_name')
        batch_op.drop_column('director_phone')
        batch_op.drop_column('director_name')
        batch_op.drop_column('social_address')

    # ### end Alembic commands ###
