"""Add practice_progress table

Revision ID: 8fd87df5b406
Revises: df35f3de010b
Create Date: 2026-02-28 19:28:57.088083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fd87df5b406'
down_revision: Union[str, None] = 'df35f3de010b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('practice_progress',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('work_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('NUEVA', 'EN_PROGRESO', 'DOMINADA', name='practicestatus'), nullable=False),
    sa.Column('minutes_practiced', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('practice_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_practice_progress_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('practice_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_practice_progress_id'))

    op.drop_table('practice_progress')
    # ### end Alembic commands ###
