"""add_direct_feedback_model

Revision ID: c66f1c34d45b
Revises: 417f65a2c3b2
Create Date: 2026-03-03 17:27:02.699074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c66f1c34d45b'
down_revision: Union[str, None] = '417f65a2c3b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('directfeedback',
    sa.Column('sender_id', sa.String(), nullable=False),
    sa.Column('recipient_id', sa.String(), nullable=False),
    sa.Column('choir_id', sa.String(), nullable=False),
    sa.Column('work_id', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['choir_id'], ['choirs.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('directfeedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_directfeedback_id'), ['id'], unique=False)

    # project_repertoire modify removed due to work_id error

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('favorite_voice', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('favorite_voice')
        batch_op.drop_column('bio')
        batch_op.drop_column('avatar_url')

    # project_repertoire downgrade removed

    with op.batch_alter_table('directfeedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_directfeedback_id'))

    op.drop_table('directfeedback')
    # ### end Alembic commands ###
