"""Init all models

Revision ID: df35f3de010b
Revises: 
Create Date: 2026-02-28 18:53:57.833454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df35f3de010b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('choirs',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('choirs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_choirs_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('DIRECTOR', 'CORALISTA', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('invites',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('choir_id', sa.String(), nullable=False),
    sa.Column('created_by_id', sa.String(), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('uses_count', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['choir_id'], ['choirs.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invites_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_invites_id'), ['id'], unique=False)

    op.create_table('memberships',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('choir_id', sa.String(), nullable=False),
    sa.Column('voice_part', sa.Enum('SOPRANO', 'ALTO', 'TENOR', 'BASS', 'DIRECTOR', name='voicepart'), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['choir_id'], ['choirs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memberships_choir_id'), ['choir_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memberships_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memberships_user_id'), ['user_id'], unique=False)

    op.create_table('seasons',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('choir_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['choir_id'], ['choirs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_seasons_choir_id'), ['choir_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_seasons_id'), ['id'], unique=False)

    op.create_table('works',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('composer', sa.String(), nullable=True),
    sa.Column('era', sa.String(), nullable=True),
    sa.Column('genre', sa.String(), nullable=True),
    sa.Column('voice_format', sa.String(), nullable=True),
    sa.Column('accompaniment', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('difficulty', sa.String(), nullable=True),
    sa.Column('choir_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['choir_id'], ['choirs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('works', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_works_choir_id'), ['choir_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_works_composer'), ['composer'], unique=False)
        batch_op.create_index(batch_op.f('ix_works_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_works_title'), ['title'], unique=False)

    op.create_table('editions',
    sa.Column('work_id', sa.String(), nullable=False),
    sa.Column('publisher', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('editions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_editions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_editions_work_id'), ['work_id'], unique=False)

    op.create_table('projects',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('choir_id', sa.String(), nullable=False),
    sa.Column('season_id', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['choir_id'], ['choirs.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_choir_id'), ['choir_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_season_id'), ['season_id'], unique=False)

    op.create_table('assets',
    sa.Column('edition_id', sa.String(), nullable=False),
    sa.Column('asset_type', sa.String(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['edition_id'], ['editions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assets_asset_type'), ['asset_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_edition_id'), ['edition_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_id'), ['id'], unique=False)

    op.create_table('project_repertoire',
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('edition_id', sa.String(), nullable=True),
    sa.Column('work_title', sa.String(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['edition_id'], ['editions.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_repertoire', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_repertoire_edition_id'), ['edition_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_repertoire_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_repertoire_project_id'), ['project_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_repertoire', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_repertoire_project_id'))
        batch_op.drop_index(batch_op.f('ix_project_repertoire_id'))
        batch_op.drop_index(batch_op.f('ix_project_repertoire_edition_id'))

    op.drop_table('project_repertoire')
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_id'))
        batch_op.drop_index(batch_op.f('ix_assets_edition_id'))
        batch_op.drop_index(batch_op.f('ix_assets_asset_type'))

    op.drop_table('assets')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_season_id'))
        batch_op.drop_index(batch_op.f('ix_projects_id'))
        batch_op.drop_index(batch_op.f('ix_projects_choir_id'))

    op.drop_table('projects')
    with op.batch_alter_table('editions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_editions_work_id'))
        batch_op.drop_index(batch_op.f('ix_editions_id'))

    op.drop_table('editions')
    with op.batch_alter_table('works', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_works_title'))
        batch_op.drop_index(batch_op.f('ix_works_id'))
        batch_op.drop_index(batch_op.f('ix_works_composer'))
        batch_op.drop_index(batch_op.f('ix_works_choir_id'))

    op.drop_table('works')
    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seasons_id'))
        batch_op.drop_index(batch_op.f('ix_seasons_choir_id'))

    op.drop_table('seasons')
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memberships_user_id'))
        batch_op.drop_index(batch_op.f('ix_memberships_id'))
        batch_op.drop_index(batch_op.f('ix_memberships_choir_id'))

    op.drop_table('memberships')
    with op.batch_alter_table('invites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invites_id'))
        batch_op.drop_index(batch_op.f('ix_invites_code'))

    op.drop_table('invites')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('choirs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_choirs_id'))

    op.drop_table('choirs')
    # ### end Alembic commands ###
