"""add_edition_part_mapping

Revision ID: eb88c4bced62
Revises: 39926feca242
Create Date: 2026-02-28 21:04:42.631635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb88c4bced62'
down_revision: Union[str, None] = '39926feca242'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edition_part_mapping',
    sa.Column('edition_id', sa.String(), nullable=False),
    sa.Column('part_name', sa.String(), nullable=False),
    sa.Column('assigned_to', sa.String(), nullable=False),
    sa.Column('auto_detected', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['edition_id'], ['editions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('edition_part_mapping', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_edition_part_mapping_edition_id'), ['edition_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edition_part_mapping_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('edition_part_mapping', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_edition_part_mapping_id'))
        batch_op.drop_index(batch_op.f('ix_edition_part_mapping_edition_id'))

    op.drop_table('edition_part_mapping')
    # ### end Alembic commands ###
